spring.datasource.url=jdbc:postgresql://localhost:5433/sivec
spring.datasource.username=postgres
spring.datasource.password=132419

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

